version_config:
  #公司大模型配置 
  big_model:
    openai_api_base: ""
    key: ""
  log_path: "./logs/"

  redis:
    host: 10.1.33.145
    port: 6379
    password: 123456
    db: 10
    expires_time: 7200
    cache: 2
    ai_code: 0
    inspection: 4
  # neo4j配置
  neo4j:
    neo4j_ip:  10.1.33.145
    username: neo4j
    password: "123456"
    port: "7474"
  # mongo配置
  mongodb:
    mongo_ip: 10.1.69.4
    username: developer
    password: "123456"
    port: "27017"
    auth: "admin"
    table: AITenderPlatform
    tb_paramter: tb_paramter
return_error_code:
  1: 未定义错误
